// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM986SI348Yki7H6vHoZiUn826k40dgs8',
    appId: '1:14196027823:web:0d9f377e7af57321f7bf5a',
    messagingSenderId: '14196027823',
    projectId: 'lsvem24-5cb7d',
    authDomain: 'lsvem24-5cb7d.firebaseapp.com',
    storageBucket: 'lsvem24-5cb7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRqfp7qc_Q_B3n6pKl4MXFbASrEn7ua0g',
    appId: '1:14196027823:android:c37f2a95e761129ef7bf5a',
    messagingSenderId: '14196027823',
    projectId: 'lsvem24-5cb7d',
    storageBucket: 'lsvem24-5cb7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOmQVhvxkWShCvAo42J9HUU0zCRUAa7rU',
    appId: '1:14196027823:ios:36ad2be9df4143bef7bf5a',
    messagingSenderId: '14196027823',
    projectId: 'lsvem24-5cb7d',
    storageBucket: 'lsvem24-5cb7d.firebasestorage.app',
    iosBundleId: 'com.lsvem24.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOmQVhvxkWShCvAo42J9HUU0zCRUAa7rU',
    appId: '1:14196027823:ios:bae17f68e23a3d26f7bf5a',
    messagingSenderId: '14196027823',
    projectId: 'lsvem24-5cb7d',
    storageBucket: 'lsvem24-5cb7d.firebasestorage.app',
    iosBundleId: 'com.meTube.live',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM986SI348Yki7H6vHoZiUn826k40dgs8',
    appId: '1:14196027823:web:cfbaf0147f0ea565f7bf5a',
    messagingSenderId: '14196027823',
    projectId: 'lsvem24-5cb7d',
    authDomain: 'lsvem24-5cb7d.firebaseapp.com',
    storageBucket: 'lsvem24-5cb7d.firebasestorage.app',
  );
}
