-keep class **.zego.**  { *; }
-keep class **.**.zego_zpns.** { *; }
-keep class io.flutter.** { *; }
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**
-dontwarn io.flutter.embedding.**